# Generated by Django 2.2.4 on 2020-03-24 09:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=20, unique=True, verbose_name='用户名')),
                ('comment', models.CharField(default='123456', max_length=200, verbose_name='评价')),
            ],
            options={
                'verbose_name': '成员',
                'verbose_name_plural': '成员',
            },
        ),
        migrations.CreateModel(
            name='WorkerState',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('statedetail', models.CharField(default='空闲', max_length=20, verbose_name='工作状态')),
            ],
        ),
        migrations.CreateModel(
            name='Worker',
            fields=[
                ('wuuid', models.AutoField(editable=False, primary_key=True, serialize=False, verbose_name='唯一标识')),
                ('workername', models.CharField(max_length=20, verbose_name='姓名')),
                ('workerID', models.CharField(max_length=100, verbose_name='身份认证')),
                ('jointime', models.DateField(auto_now=True, verbose_name='加入时间')),
                ('state', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='workerstate_id', to='baseapp_1.WorkerState', verbose_name='状态')),
            ],
            options={
                'verbose_name': '操作员',
                'verbose_name_plural': '操作员',
            },
        ),
    ]
