# Generated by Django 2.2.4 on 2020-03-18 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BaseApp_1', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': '成员', 'verbose_name_plural': '成员'},
        ),
        migrations.RemoveField(
            model_name='user',
            name='password',
        ),
        migrations.AddField(
            model_name='user',
            name='comment',
            field=models.CharField(default='123456', max_length=200, verbose_name='评价'),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(max_length=20, verbose_name='用户名'),
        ),
    ]
