# Generated by Django 2.2.4 on 2020-03-19 01:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('BaseApp_1', '0003_auto_20200318_1124'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkerState',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('statedetail', models.CharField(default='空闲', max_length=20, verbose_name='工作状态')),
            ],
        ),
        migrations.CreateModel(
            name='Worker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('workername', models.CharField(max_length=20, verbose_name='姓名')),
                ('workerID', models.CharField(max_length=100, unique=True, verbose_name='身份认证')),
                ('jointime', models.DateField(auto_now=True, verbose_name='加入时间')),
                ('state', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='workerstate_id', to='BaseApp_1.WorkerState')),
            ],
            options={
                'verbose_name': '操作员',
                'verbose_name_plural': '操作员',
            },
        ),
    ]
