# Generated by Django 2.2.4 on 2020-03-19 04:38

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('BaseApp_1', '0004_worker_workerstate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='worker',
            name='id',
        ),
        migrations.AddField(
            model_name='worker',
            name='wuuid',
            field=models.UUIDField(default=uuid.UUID('4e5628f5-0edb-40bc-9e70-e4423562a05a'), editable=False, primary_key=True, serialize=False),
        ),
    ]
