# Generated by Django 2.2.4 on 2020-03-19 05:11

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('BaseApp_1', '0005_auto_20200319_1238'),
    ]

    operations = [
        migrations.AlterField(
            model_name='worker',
            name='wuuid',
            field=models.UUIDField(default=uuid.UUID('01da7478-a1be-4cc8-92b1-6bb3d029cb44'), editable=False, primary_key=True, serialize=False),
        ),
    ]
