# Generated by Django 2.2.4 on 2020-03-19 05:13

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('BaseApp_1', '0006_auto_20200319_1311'),
    ]

    operations = [
        migrations.AlterField(
            model_name='worker',
            name='wuuid',
            field=models.UUIDField(default=uuid.UUID('3ee48de1-1160-4f63-b239-3d1344c3a808'), editable=False, primary_key=True, serialize=False),
        ),
    ]
