# Generated by Django 2.2.4 on 2020-03-19 05:15

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('BaseApp_1', '0007_auto_20200319_1313'),
    ]

    operations = [
        migrations.AlterField(
            model_name='worker',
            name='wuuid',
            field=models.UUIDField(default=uuid.UUID('3f87ddf9-3fa8-484b-9750-bc180544aa04'), editable=False, primary_key=True, serialize=False),
        ),
    ]
