# Generated by Django 2.2.4 on 2020-03-19 09:12

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('BaseApp_1', '0008_auto_20200319_1315'),
    ]

    operations = [
        migrations.AlterField(
            model_name='worker',
            name='wuuid',
            field=models.UUIDField(default=uuid.UUID('7b6a2904-6afb-490d-9f60-098abfadeb0c'), editable=False, primary_key=True, serialize=False),
        ),
    ]
