# Generated by Django 2.2.4 on 2020-03-19 09:14

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('BaseApp_1', '0009_auto_20200319_1712'),
    ]

    operations = [
        migrations.AlterField(
            model_name='worker',
            name='wuuid',
            field=models.UUIDField(default=uuid.UUID('67225540-5559-4e56-b4f8-726b45eccefd'), editable=False, primary_key=True, serialize=False),
        ),
    ]
