# Generated by Django 2.2.4 on 2020-03-19 09:22

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('BaseApp_1', '0010_auto_20200319_1714'),
    ]

    operations = [
        migrations.AlterField(
            model_name='worker',
            name='wuuid',
            field=models.UUIDField(default=uuid.UUID('105ebffc-a03b-4a38-9006-8af3e37e2161'), editable=False, primary_key=True, serialize=False),
        ),
    ]
