# Generated by Django 2.2.4 on 2020-03-20 01:16

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('BaseApp_1', '0011_auto_20200319_1722'),
    ]

    operations = [
        migrations.AlterField(
            model_name='worker',
            name='wuuid',
            field=models.UUIDField(default=uuid.UUID('bca6b496-5522-4be1-a761-45afb0cf322b'), editable=False, primary_key=True, serialize=False),
        ),
    ]
