# Generated by Django 2.2.4 on 2020-03-20 10:22

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('BaseApp_1', '0012_auto_20200320_0916'),
    ]

    operations = [
        migrations.AlterField(
            model_name='worker',
            name='state',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='workerstate_id', to='BaseApp_1.WorkerState', verbose_name='状态'),
        ),
        migrations.AlterField(
            model_name='worker',
            name='workerID',
            field=models.CharField(max_length=100, verbose_name='身份认证'),
        ),
        migrations.AlterField(
            model_name='worker',
            name='wuuid',
            field=models.UUIDField(default=uuid.UUID('ee6c7131-07bd-42ce-98fa-c82d75cf637d'), editable=False, primary_key=True, serialize=False),
        ),
    ]
