# Generated by Django 2.2.4 on 2020-03-20 10:58

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('BaseApp_1', '0013_auto_20200320_1022'),
    ]

    operations = [
        migrations.AlterField(
            model_name='worker',
            name='wuuid',
            field=models.CharField(default=uuid.UUID('fb6e9efa-daee-579e-b445-0ab2dbe74568'), editable=False, max_length=100, primary_key=True, serialize=False, verbose_name='唯一标识'),
        ),
    ]
