# Generated by Django 2.2.4 on 2020-03-19 00:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TaskMSApp', '0002_task_starter'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='state',
            field=models.CharField(default='', max_length=20, verbose_name='状态'),
        ),
        migrations.AddField(
            model_name='task',
            name='worker',
            field=models.CharField(default='', max_length=20, verbose_name='操作员'),
        ),
    ]
