# Generated by Django 2.2.4 on 2020-03-19 00:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('TaskMSApp', '0003_auto_20200319_0831'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='starter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_username', to='BaseApp_1.User'),
        ),
    ]
