# Generated by Django 2.2.4 on 2020-03-19 00:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('TaskMSApp', '0004_auto_20200319_0852'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='starter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_id', to='BaseApp_1.User'),
        ),
    ]
