# Generated by Django 2.2.4 on 2020-03-19 01:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('TaskMSApp', '0005_auto_20200319_0855'),
    ]

    operations = [
        migrations.CreateModel(
            name='StateCode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('statedetails', models.CharField(default='未完成', max_length=20, verbose_name='状态')),
            ],
        ),
        migrations.AlterField(
            model_name='task',
            name='state',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='statecode_id', to='TaskMSApp.StateCode'),
        ),
    ]
