# Generated by Django 2.2.4 on 2020-03-19 01:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('TaskMSApp', '0006_auto_20200319_0904'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='state',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='statecode_id', to='TaskMSApp.StateCode'),
        ),
    ]
