# Generated by Django 2.2.4 on 2020-03-19 03:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('TaskMSApp', '0007_auto_20200319_0907'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='starter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_id', to='BaseApp_1.User', verbose_name='发起人'),
        ),
        migrations.AlterField(
            model_name='task',
            name='state',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='statecode_id', to='TaskMSApp.StateCode', verbose_name='完成状态'),
        ),
        migrations.AlterField(
            model_name='task',
            name='worker',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='worker_id', to='BaseApp_1.Worker', verbose_name='操作员'),
        ),
    ]
