# Generated by Django 2.2.4 on 2020-03-19 05:11

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('TaskMSApp', '0008_auto_20200319_1122'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='id',
        ),
        migrations.AddField(
            model_name='task',
            name='tuuid',
            field=models.UUIDField(default=uuid.UUID('4f8c9ece-5971-48ea-b23c-d1d9f7e2c885'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='task',
            name='worker',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='worker_uuid', to='BaseApp_1.Worker', verbose_name='操作员'),
        ),
    ]
