# Generated by Django 2.2.4 on 2020-03-19 05:13

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('TaskMSApp', '0009_auto_20200319_1311'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='tuuid',
            field=models.UUIDField(default=uuid.UUID('5c7cf0f0-82b9-47ef-a6c6-b39cb23770e6'), editable=False, primary_key=True, serialize=False),
        ),
    ]
