# Generated by Django 2.2.4 on 2020-03-19 05:15

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('TaskMSApp', '0010_auto_20200319_1313'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='tuuid',
            field=models.UUIDField(default=uuid.UUID('c646b207-fa95-4c32-9d2c-0bbc91e2f037'), editable=False, primary_key=True, serialize=False),
        ),
    ]
