# Generated by Django 2.2.4 on 2020-03-19 09:12

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('TaskMSApp', '0011_auto_20200319_1315'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='endTime',
            field=models.DateTimeField(auto_now=True, verbose_name='结束时间'),
        ),
        migrations.AddField(
            model_name='task',
            name='primary',
            field=models.IntegerField(default=1, verbose_name='优先级'),
        ),
        migrations.AddField(
            model_name='task',
            name='startTime',
            field=models.DateTimeField(auto_now=True, verbose_name='开始时间'),
        ),
        migrations.AlterField(
            model_name='task',
            name='tuuid',
            field=models.UUIDField(default=uuid.UUID('d5ba92d9-9561-4be0-b837-b6980ca43ba1'), editable=False, primary_key=True, serialize=False),
        ),
    ]
