# Generated by Django 2.2.4 on 2020-03-19 09:14

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('TaskMSApp', '0012_auto_20200319_1712'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='endTime',
            field=models.DateTimeField(verbose_name='结束时间'),
        ),
        migrations.AlterField(
            model_name='task',
            name='tuuid',
            field=models.UUIDField(default=uuid.UUID('6c6cde35-6c32-4bf1-8ac8-ade426ac68f5'), editable=False, primary_key=True, serialize=False),
        ),
    ]
