# Generated by Django 2.2.4 on 2020-03-19 09:22

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('TaskMSApp', '0013_auto_20200319_1714'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='endTime',
            field=models.DateTimeField(blank=True, editable=False, null=True, verbose_name='结束时间'),
        ),
        migrations.AlterField(
            model_name='task',
            name='primary',
            field=models.IntegerField(default=1, max_length=3, verbose_name='优先级'),
        ),
        migrations.AlterField(
            model_name='task',
            name='tuuid',
            field=models.UUIDField(default=uuid.UUID('605bf1ad-9e1f-4349-884f-2c7e32cd43be'), editable=False, primary_key=True, serialize=False),
        ),
    ]
