# Generated by Django 2.2.4 on 2020-03-20 01:16

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('TaskMSApp', '0014_auto_20200319_1722'),
    ]

    operations = [
        migrations.CreateModel(
            name='PrimaryLevel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('primarylevel', models.CharField(default='一般', max_length=20, verbose_name='优先级')),
            ],
        ),
        migrations.AlterField(
            model_name='task',
            name='primary',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='primarylevel_id', to='TaskMSApp.PrimaryLevel', verbose_name='优先级'),
        ),
        migrations.AlterField(
            model_name='task',
            name='tuuid',
            field=models.UUIDField(default=uuid.UUID('c4b00ea7-d266-4931-8e84-0c36dd2fa479'), editable=False, primary_key=True, serialize=False),
        ),
    ]
