# Generated by Django 2.2.4 on 2020-03-20 10:22

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('TaskMSApp', '0015_auto_20200320_0916'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='tuuid',
            field=models.UUIDField(default=uuid.UUID('5f45f3ed-be27-409a-bb7c-58ca86b16c7f'), editable=False, primary_key=True, serialize=False, verbose_name='唯一标识'),
        ),
    ]
