# Generated by Django 2.2.4 on 2020-03-20 10:58

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('TaskMSApp', '0016_auto_20200320_1022'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='tuuid',
            field=models.CharField(default=uuid.UUID('1c5a2244-bd77-5c9d-a2c6-aaf715e323a3'), editable=False, max_length=100, primary_key=True, serialize=False, verbose_name='唯一标识'),
        ),
    ]
