# Generated by Django 2.2.4 on 2020-03-20 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TaskMSApp', '0017_auto_20200320_1058'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='tuuid',
            field=models.IntegerField(editable=False, primary_key=True, serialize=False, verbose_name='唯一标识'),
        ),
    ]
